name: lab3
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter
  - notebook
  - numpy
  - pandas
  - matplotlib  
  - wordcloud
  - scikit-learn  
  - mlxtend
  - seaborn
  - pip
  - pip:
    - textmining3
    - graphviz
